name: Delete Cloudinary Files

on:
  schedule:
    - cron: '0 3 * * *' # roda todo dia às 03:00
  workflow_dispatch:

jobs:
  delete:
    runs-on: ubuntu-latest

    steps:
      - name: Clonar repositório
        uses: actions/checkout@v3

      - name: Instalar Node
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Instalar dependências
        run: npm install cloudinary

      - name: Rodar script
        run: node delete.js
        env:
          CLOUDINARY_CLOUD_NAME: ${{ secrets.CLOUDINARY_CLOUD_NAME }}
          CLOUDINARY_API_KEY: ${{ secrets.CLOUDINARY_API_KEY }}
          CLOUDINARY_API_SECRET: ${{ secrets.CLOUDINARY_API_SECRET }}

      - name: Salvar alterações
        run: |
          git config user.name "bot"
          git config user.email "bot@github.com"
          git add logs.json
          git commit -m "Atualizando logs" || echo "Sem mudanças"
          git push
